language: go

go:
- 1.1
- 1.2
- 1.3
- 1.4

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install snmpd
 - echo '127.0.0.1 gosnmp-test-host' | sudo tee -a /etc/hosts

install:
 - go get github.com/soniah/gosnmp
 - sudo ./snmp_users.sh
 - sudo /etc/init.d/snmpd restart

script:
 - go test
